import fc from "fast-check"
import {Spec} from "./jest"

export interface ItPropOptions<Ts = void> extends fc.Parameters<Ts> {
    integration?: boolean
    isolate?: boolean
    timeout?: number
}

export interface ItProp<ReturnType = Promise<void>> {
    <T0>(
        name: string,
        arb0: fc.Arbitrary<T0>,
        callback: (arg0: T0, spec: Spec) => ReturnType,
        options?: ItPropOptions<[T0]>,
    ): Spec

    <T0, T1>(
        name: string,
        arb0: fc.Arbitrary<T0>,
        arb1: fc.Arbitrary<T1>,
        callback: (arg0: T0, arg1: T1, spec: Spec) => ReturnType,
        options?: ItPropOptions<[T0, T1]>,
    ): Spec

    <T0, T1, T2>(
        name: string,
        arb0: fc.Arbitrary<T0>,
        arb1: fc.Arbitrary<T1>,
        arb2: fc.Arbitrary<T2>,
        callback: (arg0: T0, arg1: T1, arg2: T2, spec: Spec) => ReturnType,
        options?: ItPropOptions<[T0, T1, T2]>,
    ): Spec

    <T0, T1, T2, T3>(
        name: string,
        arb0: fc.Arbitrary<T0>,
        arb1: fc.Arbitrary<T1>,
        arb2: fc.Arbitrary<T2>,
        arb3: fc.Arbitrary<T3>,
        callback: (
            arg0: T0,
            arg1: T1,
            arg2: T2,
            arg3: T3,
            spec: Spec,
        ) => ReturnType,
        options?: ItPropOptions<[T0, T1, T2, T3]>,
    ): Spec

    <T0, T1, T2, T3, T4>(
        name: string,
        arb0: fc.Arbitrary<T0>,
        arb1: fc.Arbitrary<T1>,
        arb2: fc.Arbitrary<T2>,
        arb3: fc.Arbitrary<T3>,
        arb4: fc.Arbitrary<T4>,
        callback: (
            arg0: T0,
            arg1: T1,
            arg2: T2,
            arg3: T3,
            arg4: T4,
            spec: Spec,
        ) => ReturnType,
        options?: ItPropOptions<[T0, T1, T2, T3, T4]>,
    ): Spec

    <T0, T1, T2, T3, T4, T5>(
        name: string,
        arb0: fc.Arbitrary<T0>,
        arb1: fc.Arbitrary<T1>,
        arb2: fc.Arbitrary<T2>,
        arb3: fc.Arbitrary<T3>,
        arb4: fc.Arbitrary<T4>,
        arb5: fc.Arbitrary<T5>,
        callback: (
            arg0: T0,
            arg1: T1,
            arg2: T2,
            arg3: T3,
            arg4: T4,
            arg5: T5,
            spec: Spec,
        ) => ReturnType,
        options?: ItPropOptions<[T0, T1, T2, T3, T4, T5]>,
    ): Spec

    <T0, T1, T2, T3, T4, T5, T6>(
        name: string,
        arb0: fc.Arbitrary<T0>,
        arb1: fc.Arbitrary<T1>,
        arb2: fc.Arbitrary<T2>,
        arb3: fc.Arbitrary<T3>,
        arb4: fc.Arbitrary<T4>,
        arb5: fc.Arbitrary<T5>,
        arb6: fc.Arbitrary<T6>,
        callback: (
            arg0: T0,
            arg1: T1,
            arg2: T2,
            arg3: T3,
            arg4: T4,
            arg5: T5,
            arg6: T6,
            spec: Spec,
        ) => ReturnType,
        options?: ItPropOptions<[T0, T1, T2, T3, T4, T5, T6]>,
    ): Spec

    <T0, T1, T2, T3, T4, T5, T6, T7>(
        name: string,
        arb0: fc.Arbitrary<T0>,
        arb1: fc.Arbitrary<T1>,
        arb2: fc.Arbitrary<T2>,
        arb3: fc.Arbitrary<T3>,
        arb4: fc.Arbitrary<T4>,
        arb5: fc.Arbitrary<T5>,
        arb6: fc.Arbitrary<T6>,
        arb7: fc.Arbitrary<T7>,
        callback: (
            arg0: T0,
            arg1: T1,
            arg2: T2,
            arg3: T3,
            arg4: T4,
            arg5: T5,
            arg6: T6,
            arg7: T7,
            spec: Spec,
        ) => ReturnType,
        options?: ItPropOptions<[T0, T1, T2, T3, T4, T5, T6, T7]>,
    ): Spec

    <T0, T1, T2, T3, T4, T5, T6, T7, T8>(
        name: string,
        arb0: fc.Arbitrary<T0>,
        arb1: fc.Arbitrary<T1>,
        arb2: fc.Arbitrary<T2>,
        arb3: fc.Arbitrary<T3>,
        arb4: fc.Arbitrary<T4>,
        arb5: fc.Arbitrary<T5>,
        arb6: fc.Arbitrary<T6>,
        arb7: fc.Arbitrary<T7>,
        arb8: fc.Arbitrary<T8>,
        callback: (
            arg0: T0,
            arg1: T1,
            arg2: T2,
            arg3: T3,
            arg4: T4,
            arg5: T5,
            arg6: T6,
            arg7: T7,
            arg8: T8,
            spec: Spec,
        ) => ReturnType,
        options?: ItPropOptions<[T0, T1, T2, T3, T4, T5, T6, T7, T8]>,
    ): Spec

    <T0, T1, T2, T3, T4, T5, T6, T7, T8, T9>(
        name: string,
        arb0: fc.Arbitrary<T0>,
        arb1: fc.Arbitrary<T1>,
        arb2: fc.Arbitrary<T2>,
        arb3: fc.Arbitrary<T3>,
        arb4: fc.Arbitrary<T4>,
        arb5: fc.Arbitrary<T5>,
        arb6: fc.Arbitrary<T6>,
        arb7: fc.Arbitrary<T7>,
        arb8: fc.Arbitrary<T8>,
        arb9: fc.Arbitrary<T9>,
        callback: (
            arg0: T0,
            arg1: T1,
            arg2: T2,
            arg3: T3,
            arg4: T4,
            arg5: T5,
            arg6: T6,
            arg7: T7,
            arg8: T8,
            arg9: T9,
            spec: Spec,
        ) => ReturnType,
        options?: ItPropOptions<[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9]>,
    ): Spec

    <T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10>(
        name: string,
        arb0: fc.Arbitrary<T0>,
        arb1: fc.Arbitrary<T1>,
        arb2: fc.Arbitrary<T2>,
        arb3: fc.Arbitrary<T3>,
        arb4: fc.Arbitrary<T4>,
        arb5: fc.Arbitrary<T5>,
        arb6: fc.Arbitrary<T6>,
        arb7: fc.Arbitrary<T7>,
        arb8: fc.Arbitrary<T8>,
        arb9: fc.Arbitrary<T9>,
        arb10: fc.Arbitrary<T10>,
        callback: (
            arg0: T0,
            arg1: T1,
            arg2: T2,
            arg3: T3,
            arg4: T4,
            arg5: T5,
            arg6: T6,
            arg7: T7,
            arg8: T8,
            arg9: T9,
            arg10: T10,
            spec: Spec,
        ) => ReturnType,
        options?: ItPropOptions<[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10]>,
    ): Spec

    <T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11>(
        name: string,
        arb0: fc.Arbitrary<T0>,
        arb1: fc.Arbitrary<T1>,
        arb2: fc.Arbitrary<T2>,
        arb3: fc.Arbitrary<T3>,
        arb4: fc.Arbitrary<T4>,
        arb5: fc.Arbitrary<T5>,
        arb6: fc.Arbitrary<T6>,
        arb7: fc.Arbitrary<T7>,
        arb8: fc.Arbitrary<T8>,
        arb9: fc.Arbitrary<T9>,
        arb10: fc.Arbitrary<T10>,
        arb11: fc.Arbitrary<T11>,
        callback: (
            arg0: T0,
            arg1: T1,
            arg2: T2,
            arg3: T3,
            arg4: T4,
            arg5: T5,
            arg6: T6,
            arg7: T7,
            arg8: T8,
            arg9: T9,
            arg10: T10,
            arg11: T11,
            spec: Spec,
        ) => ReturnType,
        options?: ItPropOptions<
            [T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11]
        >,
    ): Spec

    <T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12>(
        name: string,
        arb0: fc.Arbitrary<T0>,
        arb1: fc.Arbitrary<T1>,
        arb2: fc.Arbitrary<T2>,
        arb3: fc.Arbitrary<T3>,
        arb4: fc.Arbitrary<T4>,
        arb5: fc.Arbitrary<T5>,
        arb6: fc.Arbitrary<T6>,
        arb7: fc.Arbitrary<T7>,
        arb8: fc.Arbitrary<T8>,
        arb9: fc.Arbitrary<T9>,
        arb10: fc.Arbitrary<T10>,
        arb11: fc.Arbitrary<T11>,
        arb12: fc.Arbitrary<T12>,
        callback: (
            arg0: T0,
            arg1: T1,
            arg2: T2,
            arg3: T3,
            arg4: T4,
            arg5: T5,
            arg6: T6,
            arg7: T7,
            arg8: T8,
            arg9: T9,
            arg10: T10,
            arg11: T11,
            arg12: T12,
            spec: Spec,
        ) => ReturnType,
        options?: ItPropOptions<
            [T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12]
        >,
    ): Spec

    <T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>(
        name: string,
        arb0: fc.Arbitrary<T0>,
        arb1: fc.Arbitrary<T1>,
        arb2: fc.Arbitrary<T2>,
        arb3: fc.Arbitrary<T3>,
        arb4: fc.Arbitrary<T4>,
        arb5: fc.Arbitrary<T5>,
        arb6: fc.Arbitrary<T6>,
        arb7: fc.Arbitrary<T7>,
        arb8: fc.Arbitrary<T8>,
        arb9: fc.Arbitrary<T9>,
        arb10: fc.Arbitrary<T10>,
        arb11: fc.Arbitrary<T11>,
        arb12: fc.Arbitrary<T12>,
        arb13: fc.Arbitrary<T13>,
        callback: (
            arg0: T0,
            arg1: T1,
            arg2: T2,
            arg3: T3,
            arg4: T4,
            arg5: T5,
            arg6: T6,
            arg7: T7,
            arg8: T8,
            arg9: T9,
            arg10: T10,
            arg11: T11,
            arg12: T12,
            arg13: T13,
            spec: Spec,
        ) => ReturnType,
        options?: ItPropOptions<
            [T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13]
        >,
    ): Spec

    <T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14>(
        name: string,
        arb0: fc.Arbitrary<T0>,
        arb1: fc.Arbitrary<T1>,
        arb2: fc.Arbitrary<T2>,
        arb3: fc.Arbitrary<T3>,
        arb4: fc.Arbitrary<T4>,
        arb5: fc.Arbitrary<T5>,
        arb6: fc.Arbitrary<T6>,
        arb7: fc.Arbitrary<T7>,
        arb8: fc.Arbitrary<T8>,
        arb9: fc.Arbitrary<T9>,
        arb10: fc.Arbitrary<T10>,
        arb11: fc.Arbitrary<T11>,
        arb12: fc.Arbitrary<T12>,
        arb13: fc.Arbitrary<T13>,
        arb14: fc.Arbitrary<T14>,
        callback: (
            arg0: T0,
            arg1: T1,
            arg2: T2,
            arg3: T3,
            arg4: T4,
            arg5: T5,
            arg6: T6,
            arg7: T7,
            arg8: T8,
            arg9: T9,
            arg10: T10,
            arg11: T11,
            arg12: T12,
            arg13: T13,
            arg14: T14,
            spec: Spec,
        ) => ReturnType,
        options?: ItPropOptions<
            [T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14]
        >,
    ): Spec

    <T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15>(
        name: string,
        arb0: fc.Arbitrary<T0>,
        arb1: fc.Arbitrary<T1>,
        arb2: fc.Arbitrary<T2>,
        arb3: fc.Arbitrary<T3>,
        arb4: fc.Arbitrary<T4>,
        arb5: fc.Arbitrary<T5>,
        arb6: fc.Arbitrary<T6>,
        arb7: fc.Arbitrary<T7>,
        arb8: fc.Arbitrary<T8>,
        arb9: fc.Arbitrary<T9>,
        arb10: fc.Arbitrary<T10>,
        arb11: fc.Arbitrary<T11>,
        arb12: fc.Arbitrary<T12>,
        arb13: fc.Arbitrary<T13>,
        arb14: fc.Arbitrary<T14>,
        arb15: fc.Arbitrary<T15>,
        callback: (
            arg0: T0,
            arg1: T1,
            arg2: T2,
            arg3: T3,
            arg4: T4,
            arg5: T5,
            arg6: T6,
            arg7: T7,
            arg8: T8,
            arg9: T9,
            arg10: T10,
            arg11: T11,
            arg12: T12,
            arg13: T13,
            arg14: T14,
            arg15: T15,
            spec: Spec,
        ) => ReturnType,
        options?: ItPropOptions<
            [
                T0,
                T1,
                T2,
                T3,
                T4,
                T5,
                T6,
                T7,
                T8,
                T9,
                T10,
                T11,
                T12,
                T13,
                T14,
                T15,
            ]
        >,
    ): Spec

    <T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16>(
        name: string,
        arb0: fc.Arbitrary<T0>,
        arb1: fc.Arbitrary<T1>,
        arb2: fc.Arbitrary<T2>,
        arb3: fc.Arbitrary<T3>,
        arb4: fc.Arbitrary<T4>,
        arb5: fc.Arbitrary<T5>,
        arb6: fc.Arbitrary<T6>,
        arb7: fc.Arbitrary<T7>,
        arb8: fc.Arbitrary<T8>,
        arb9: fc.Arbitrary<T9>,
        arb10: fc.Arbitrary<T10>,
        arb11: fc.Arbitrary<T11>,
        arb12: fc.Arbitrary<T12>,
        arb13: fc.Arbitrary<T13>,
        arb14: fc.Arbitrary<T14>,
        arb15: fc.Arbitrary<T15>,
        arb16: fc.Arbitrary<T16>,
        callback: (
            arg0: T0,
            arg1: T1,
            arg2: T2,
            arg3: T3,
            arg4: T4,
            arg5: T5,
            arg6: T6,
            arg7: T7,
            arg8: T8,
            arg9: T9,
            arg10: T10,
            arg11: T11,
            arg12: T12,
            arg13: T13,
            arg14: T14,
            arg15: T15,
            arg16: T16,
            spec: Spec,
        ) => ReturnType,
        options?: ItPropOptions<
            [
                T0,
                T1,
                T2,
                T3,
                T4,
                T5,
                T6,
                T7,
                T8,
                T9,
                T10,
                T11,
                T12,
                T13,
                T14,
                T15,
                T16,
            ]
        >,
    ): Spec

    <
        T0,
        T1,
        T2,
        T3,
        T4,
        T5,
        T6,
        T7,
        T8,
        T9,
        T10,
        T11,
        T12,
        T13,
        T14,
        T15,
        T16,
        T17
    >(
        name: string,
        arb0: fc.Arbitrary<T0>,
        arb1: fc.Arbitrary<T1>,
        arb2: fc.Arbitrary<T2>,
        arb3: fc.Arbitrary<T3>,
        arb4: fc.Arbitrary<T4>,
        arb5: fc.Arbitrary<T5>,
        arb6: fc.Arbitrary<T6>,
        arb7: fc.Arbitrary<T7>,
        arb8: fc.Arbitrary<T8>,
        arb9: fc.Arbitrary<T9>,
        arb10: fc.Arbitrary<T10>,
        arb11: fc.Arbitrary<T11>,
        arb12: fc.Arbitrary<T12>,
        arb13: fc.Arbitrary<T13>,
        arb14: fc.Arbitrary<T14>,
        arb15: fc.Arbitrary<T15>,
        arb16: fc.Arbitrary<T16>,
        arb17: fc.Arbitrary<T17>,
        callback: (
            arg0: T0,
            arg1: T1,
            arg2: T2,
            arg3: T3,
            arg4: T4,
            arg5: T5,
            arg6: T6,
            arg7: T7,
            arg8: T8,
            arg9: T9,
            arg10: T10,
            arg11: T11,
            arg12: T12,
            arg13: T13,
            arg14: T14,
            arg15: T15,
            arg16: T16,
            arg17: T17,
            spec: Spec,
        ) => ReturnType,
        options?: ItPropOptions<
            [
                T0,
                T1,
                T2,
                T3,
                T4,
                T5,
                T6,
                T7,
                T8,
                T9,
                T10,
                T11,
                T12,
                T13,
                T14,
                T15,
                T16,
                T17,
            ]
        >,
    ): Spec

    <
        T0,
        T1,
        T2,
        T3,
        T4,
        T5,
        T6,
        T7,
        T8,
        T9,
        T10,
        T11,
        T12,
        T13,
        T14,
        T15,
        T16,
        T17,
        T18
    >(
        name: string,
        arb0: fc.Arbitrary<T0>,
        arb1: fc.Arbitrary<T1>,
        arb2: fc.Arbitrary<T2>,
        arb3: fc.Arbitrary<T3>,
        arb4: fc.Arbitrary<T4>,
        arb5: fc.Arbitrary<T5>,
        arb6: fc.Arbitrary<T6>,
        arb7: fc.Arbitrary<T7>,
        arb8: fc.Arbitrary<T8>,
        arb9: fc.Arbitrary<T9>,
        arb10: fc.Arbitrary<T10>,
        arb11: fc.Arbitrary<T11>,
        arb12: fc.Arbitrary<T12>,
        arb13: fc.Arbitrary<T13>,
        arb14: fc.Arbitrary<T14>,
        arb15: fc.Arbitrary<T15>,
        arb16: fc.Arbitrary<T16>,
        arb17: fc.Arbitrary<T17>,
        arb18: fc.Arbitrary<T18>,
        callback: (
            arg0: T0,
            arg1: T1,
            arg2: T2,
            arg3: T3,
            arg4: T4,
            arg5: T5,
            arg6: T6,
            arg7: T7,
            arg8: T8,
            arg9: T9,
            arg10: T10,
            arg11: T11,
            arg12: T12,
            arg13: T13,
            arg14: T14,
            arg15: T15,
            arg16: T16,
            arg17: T17,
            arg18: T18,
            spec: Spec,
        ) => ReturnType,
        options?: ItPropOptions<
            [
                T0,
                T1,
                T2,
                T3,
                T4,
                T5,
                T6,
                T7,
                T8,
                T9,
                T10,
                T11,
                T12,
                T13,
                T14,
                T15,
                T16,
                T17,
                T18,
            ]
        >,
    ): Spec

    <
        T0,
        T1,
        T2,
        T3,
        T4,
        T5,
        T6,
        T7,
        T8,
        T9,
        T10,
        T11,
        T12,
        T13,
        T14,
        T15,
        T16,
        T17,
        T18,
        T19
    >(
        name: string,
        arb0: fc.Arbitrary<T0>,
        arb1: fc.Arbitrary<T1>,
        arb2: fc.Arbitrary<T2>,
        arb3: fc.Arbitrary<T3>,
        arb4: fc.Arbitrary<T4>,
        arb5: fc.Arbitrary<T5>,
        arb6: fc.Arbitrary<T6>,
        arb7: fc.Arbitrary<T7>,
        arb8: fc.Arbitrary<T8>,
        arb9: fc.Arbitrary<T9>,
        arb10: fc.Arbitrary<T10>,
        arb11: fc.Arbitrary<T11>,
        arb12: fc.Arbitrary<T12>,
        arb13: fc.Arbitrary<T13>,
        arb14: fc.Arbitrary<T14>,
        arb15: fc.Arbitrary<T15>,
        arb16: fc.Arbitrary<T16>,
        arb17: fc.Arbitrary<T17>,
        arb18: fc.Arbitrary<T18>,
        arb19: fc.Arbitrary<T19>,
        callback: (
            arg0: T0,
            arg1: T1,
            arg2: T2,
            arg3: T3,
            arg4: T4,
            arg5: T5,
            arg6: T6,
            arg7: T7,
            arg8: T8,
            arg9: T9,
            arg10: T10,
            arg11: T11,
            arg12: T12,
            arg13: T13,
            arg14: T14,
            arg15: T15,
            arg16: T16,
            arg17: T17,
            arg18: T18,
            arg19: T19,
            spec: Spec,
        ) => ReturnType,
        options?: ItPropOptions<
            [
                T0,
                T1,
                T2,
                T3,
                T4,
                T5,
                T6,
                T7,
                T8,
                T9,
                T10,
                T11,
                T12,
                T13,
                T14,
                T15,
                T16,
                T17,
                T18,
                T19,
            ]
        >,
    ): Spec

    <
        T0,
        T1,
        T2,
        T3,
        T4,
        T5,
        T6,
        T7,
        T8,
        T9,
        T10,
        T11,
        T12,
        T13,
        T14,
        T15,
        T16,
        T17,
        T18,
        T19,
        T20
    >(
        name: string,
        arb0: fc.Arbitrary<T0>,
        arb1: fc.Arbitrary<T1>,
        arb2: fc.Arbitrary<T2>,
        arb3: fc.Arbitrary<T3>,
        arb4: fc.Arbitrary<T4>,
        arb5: fc.Arbitrary<T5>,
        arb6: fc.Arbitrary<T6>,
        arb7: fc.Arbitrary<T7>,
        arb8: fc.Arbitrary<T8>,
        arb9: fc.Arbitrary<T9>,
        arb10: fc.Arbitrary<T10>,
        arb11: fc.Arbitrary<T11>,
        arb12: fc.Arbitrary<T12>,
        arb13: fc.Arbitrary<T13>,
        arb14: fc.Arbitrary<T14>,
        arb15: fc.Arbitrary<T15>,
        arb16: fc.Arbitrary<T16>,
        arb17: fc.Arbitrary<T17>,
        arb18: fc.Arbitrary<T18>,
        arb19: fc.Arbitrary<T19>,
        arb20: fc.Arbitrary<T20>,
        callback: (
            arg0: T0,
            arg1: T1,
            arg2: T2,
            arg3: T3,
            arg4: T4,
            arg5: T5,
            arg6: T6,
            arg7: T7,
            arg8: T8,
            arg9: T9,
            arg10: T10,
            arg11: T11,
            arg12: T12,
            arg13: T13,
            arg14: T14,
            arg15: T15,
            arg16: T16,
            arg17: T17,
            arg18: T18,
            arg19: T19,
            arg20: T20,
            spec: Spec,
        ) => ReturnType,
        options?: ItPropOptions<
            [
                T0,
                T1,
                T2,
                T3,
                T4,
                T5,
                T6,
                T7,
                T8,
                T9,
                T10,
                T11,
                T12,
                T13,
                T14,
                T15,
                T16,
                T17,
                T18,
                T19,
                T20,
            ]
        >,
    ): Spec

    <
        T0,
        T1,
        T2,
        T3,
        T4,
        T5,
        T6,
        T7,
        T8,
        T9,
        T10,
        T11,
        T12,
        T13,
        T14,
        T15,
        T16,
        T17,
        T18,
        T19,
        T20,
        T21
    >(
        name: string,
        arb0: fc.Arbitrary<T0>,
        arb1: fc.Arbitrary<T1>,
        arb2: fc.Arbitrary<T2>,
        arb3: fc.Arbitrary<T3>,
        arb4: fc.Arbitrary<T4>,
        arb5: fc.Arbitrary<T5>,
        arb6: fc.Arbitrary<T6>,
        arb7: fc.Arbitrary<T7>,
        arb8: fc.Arbitrary<T8>,
        arb9: fc.Arbitrary<T9>,
        arb10: fc.Arbitrary<T10>,
        arb11: fc.Arbitrary<T11>,
        arb12: fc.Arbitrary<T12>,
        arb13: fc.Arbitrary<T13>,
        arb14: fc.Arbitrary<T14>,
        arb15: fc.Arbitrary<T15>,
        arb16: fc.Arbitrary<T16>,
        arb17: fc.Arbitrary<T17>,
        arb18: fc.Arbitrary<T18>,
        arb19: fc.Arbitrary<T19>,
        arb20: fc.Arbitrary<T20>,
        arb21: fc.Arbitrary<T21>,
        callback: (
            arg0: T0,
            arg1: T1,
            arg2: T2,
            arg3: T3,
            arg4: T4,
            arg5: T5,
            arg6: T6,
            arg7: T7,
            arg8: T8,
            arg9: T9,
            arg10: T10,
            arg11: T11,
            arg12: T12,
            arg13: T13,
            arg14: T14,
            arg15: T15,
            arg16: T16,
            arg17: T17,
            arg18: T18,
            arg19: T19,
            arg20: T20,
            arg21: T21,
            spec: Spec,
        ) => ReturnType,
        options?: ItPropOptions<
            [
                T0,
                T1,
                T2,
                T3,
                T4,
                T5,
                T6,
                T7,
                T8,
                T9,
                T10,
                T11,
                T12,
                T13,
                T14,
                T15,
                T16,
                T17,
                T18,
                T19,
                T20,
                T21,
            ]
        >,
    ): Spec
}
